// Genere depuis referentiel_produits_idj.csv.
// Version des donnees : toute modification de ce fichier change l'empreinte,
// ce qui invalide automatiquement les reglages locaux des postes.
const REFERENTIEL_VERSION = "4db6484f6dfe";   // 32 produits
const REFERENTIEL = [
 {
  "code": "CDV",
  "produit": "CARTES DE VISITE",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 9.0,
  "haut_cm": 5.5,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "FLY-A6",
  "produit": "FLYERS A6",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 10.0,
  "haut_cm": 15.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "A VALIDER : 10x15 n est pas de l A6 normalise (10,5x14,8). Tolerance portee a 5 mm pour absorber les fichiers Canva en A6 reel."
 },
 {
  "code": "FLY-A5",
  "produit": "FLYERS A5",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 15.0,
  "haut_cm": 21.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "A VALIDER : 15x21 n est pas de l A5 normalise (14,8x21). Tolerance portee a 5 mm."
 },
 {
  "code": "FLY-A4",
  "produit": "FLYERS A4",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 29.7,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "FLY-DL",
  "produit": "FLYERS DL",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 10.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "CAR-A6",
  "produit": "CARTON A6",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 10.0,
  "haut_cm": 15.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Grammage 300 g"
 },
 {
  "code": "CAR-A5",
  "produit": "CARTON A5",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 15.0,
  "haut_cm": 21.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Grammage 300 g"
 },
 {
  "code": "CAR-A4",
  "produit": "CARTON A4",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 29.7,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Grammage 300 g"
 },
 {
  "code": "CAR-A3",
  "produit": "CARTON A3",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 29.7,
  "haut_cm": 42.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "A VALIDER : present dans la liste des dimensions du document source mais absent du catalogue produits."
 },
 {
  "code": "CAR-DL",
  "produit": "CARTON DL",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 10.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "AFF-A3",
  "produit": "AFFICHES A3",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 29.7,
  "haut_cm": 42.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Impression au recto seul : une affiche se colle au mur, son verso ne se voit pas."
 },
 {
  "code": "DEP-A4",
  "produit": "DEPLIANTS",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 29.7,
  "haut_cm": 21.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PAYSAGE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_OBLIGATOIRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "ROULE3:100,99,98",
  "marge_pli_mm": 5.0,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "CORRIGE : le document source indiquait \"portrait uniquement\" pour un format 29,7x21 qui est du paysage."
 },
 {
  "code": "BRO-A4",
  "produit": "BROCHURE A4",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 29.7,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "MULTIPLE4",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": 8.0,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Pages de lecture 21 x 29,7 livrees une par une. L'imposition en cahier est faite par l'imprimerie : chaque feuille a plat est un A3 paysage 42 x 29,7. Nombre de pages multiple de 4 obligatoire."
 },
 {
  "code": "BRO-A5",
  "produit": "BROCHURE A5",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 14.8,
  "haut_cm": 21.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "MULTIPLE4",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": 8.0,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Pages de lecture 14,8 x 21 livrees une par une. Chaque feuille a plat est un A4 paysage 29,7 x 21. Nombre de pages multiple de 4 obligatoire."
 },
 {
  "code": "ETI-PAP",
  "produit": "ETIQUETTES PAPIER",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "PLAGE",
  "larg_cm": 5.0,
  "haut_cm": 5.0,
  "larg_max_cm": 29.0,
  "haut_max_cm": 40.0,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "RU-STD",
  "produit": "ROLL UP STANDARD",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "FIXE",
  "larg_cm": 85.0,
  "haut_cm": 205.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "A TRANCHER : 205 cm est-il la hauteur imprimee totale ou la hauteur visible ? Prevoir la hauteur masquee par la cassette dans les dimensions commandees."
 },
 {
  "code": "RU-GEANT",
  "produit": "ROLL UP GEANT",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "FIXE",
  "larg_cm": 150.0,
  "haut_cm": 205.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "A TRANCHER : le document source indique 150x200 dans le catalogue et 150x205 dans la liste des dimensions. Valeur retenue ici : 205."
 },
 {
  "code": "KAK-60",
  "produit": "KAKEMONO 60",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "FIXE",
  "larg_cm": 60.0,
  "haut_cm": 160.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Prevoir le debord des fourreaux haut et bas dans les dimensions commandees si pose sur barres."
 },
 {
  "code": "KAK-80",
  "produit": "KAKEMONO 80",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "FIXE",
  "larg_cm": 80.0,
  "haut_cm": 180.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Prevoir le debord des fourreaux haut et bas dans les dimensions commandees si pose sur barres."
 },
 {
  "code": "PAN-BIPLEX",
  "produit": "PANNEAU BIPLEX",
  "famille": "SIGNALETIQUE",
  "matiere": "BIPLEX",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "MAXI",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": 120.0,
  "haut_max_cm": 80.0,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "A RENSEIGNER : epaisseur reellement stockee, indispensable au module chutes. Dimension libre jusqu au maxi."
 },
 {
  "code": "PAN-ALU",
  "produit": "PANNEAU ALU",
  "famille": "SIGNALETIQUE",
  "matiere": "ALUPANEL",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "MAXI",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": 240.0,
  "haut_max_cm": 120.0,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "A RENSEIGNER : epaisseur reellement stockee, indispensable au module chutes. Dimension libre jusqu au maxi."
 },
 {
  "code": "PAN-PVC",
  "produit": "PANNEAU PVC",
  "famille": "SIGNALETIQUE",
  "matiere": "PVC",
  "epaisseur_mm": 6.0,
  "classe": "P2",
  "regle_dim": "MAXI",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": 240.0,
  "haut_max_cm": 120.0,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Dimension libre jusqu au maxi."
 },
 {
  "code": "STICKER",
  "produit": "STICKERS",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "MINI",
  "larg_cm": 3.0,
  "haut_cm": 3.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "CORRIGE : la marge de securite de 5 cm du document source est inapplicable sur un sticker de 3x3 cm. Ramenee a 5 mm."
 },
 {
  "code": "VIN-STD",
  "produit": "VINYLE STANDARD",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "MINI",
  "larg_cm": 3.0,
  "haut_cm": 3.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "CORRIGE : marge de securite ramenee a 5 mm, meme motif que les stickers."
 },
 {
  "code": "BAND-2M",
  "produit": "BANDEROLE 2 M",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "FIXE",
  "larg_cm": 200.0,
  "haut_cm": 90.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PAYSAGE",
  "tolerance_mm": 10.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 8.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Format impose : 200 x 90 cm, 6 oeillets, sans ourlet. Pour un autre format, utiliser BACHE SUR MESURE."
 },
 {
  "code": "BAND-3M",
  "produit": "BANDEROLE 3 M",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "FIXE",
  "larg_cm": 300.0,
  "haut_cm": 90.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PAYSAGE",
  "tolerance_mm": 10.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 8.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Format impose : 300 x 90 cm, 8 oeillets, sans ourlet. Pour un autre format, utiliser BACHE SUR MESURE."
 },
 {
  "code": "AFF-GDFT",
  "produit": "AFFICHE GRAND FORMAT",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "MINI",
  "larg_cm": 40.0,
  "haut_cm": 40.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "VIN-BRUT",
  "produit": "VINYLE BRUT",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 2.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Le mini de 2 m2 est un minimum de FACTURATION, pas un critere de conformite fichier."
 },
 {
  "code": "MICROPERF",
  "produit": "MICROPERFORE",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 1.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Le mini de 1 m2 est un minimum de FACTURATION, pas un critere de conformite fichier."
 },
 {
  "code": "BACHE-BRUT",
  "produit": "BACHE BRUT",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 1.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Le mini de 1 m2 est un minimum de FACTURATION, pas un critere de conformite fichier."
 },
 {
  "code": "BACHE-MES",
  "produit": "BACHE SUR MESURE",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 10.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 1.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "Bache finie, avec oeillets, sans ourlet. Dimension libre : c'est celle du fichier livre, la coupe se fait a la main. Oeillets tous les metres environ sur le pourtour, au minimum aux quatre coins."
 },
 {
  "code": "PAN-PLEXI",
  "produit": "PLEXIGLAS",
  "famille": "SIGNALETIQUE",
  "matiere": "PLEXI",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "MAXI",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": 200.0,
  "haut_max_cm": 100.0,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0.0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": null,
  "prix_m2": null,
  "prix_unite": null,
  "note": "A VALIDER : dimensions maximales du plexi a confirmer (200x100 cm retenu par defaut)."
 }
];
