// Genere depuis referentiel_produits_idj.csv.
// Version des donnees : toute modification de ce fichier change l'empreinte,
// ce qui invalide automatiquement les reglages locaux des postes.
const REFERENTIEL_VERSION = "8ca5f37a03d1";   // 33 produits
const REFERENTIEL = [
 {
  "code": "CDV",
  "produit": "CARTES DE VISITE",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 9.0,
  "haut_cm": 5.5,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "100:19;200:38;300:49;500:59;1000:89",
  "paliers_rv": "100:29;200:58;300:79;500:99;1000:159",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "FLY-A6",
  "produit": "FLYERS A6",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 10.0,
  "haut_cm": 15.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "100:29;200:39;300:49;500:59;1000:99;2000:149;3000:199;5000:299",
  "paliers_rv": "100:39;200:49;300:59;500:79;1000:159;2000:309;3000:499;5000:750",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "A VALIDER : 10x15 n est pas de l A6 normalise (10,5x14,8). Tolerance portee a 5 mm pour absorber les fichiers Canva en A6 reel."
 },
 {
  "code": "FLY-A5",
  "produit": "FLYERS A5",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 15.0,
  "haut_cm": 21.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "100:59;200:69;300:79;500:99;1000:149;2000:199;3000:299;5000:499",
  "paliers_rv": "100:79;200:89;300:99;500:129;1000:199;2000:299;3000:469;5000:779",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "A VALIDER : 15x21 n est pas de l A5 normalise (14,8x21). Tolerance portee a 5 mm."
 },
 {
  "code": "FLY-A4",
  "produit": "FLYERS A4",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 29.7,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "10:10;100:69;500:220;1000:400;1500:599;2500:1000",
  "paliers_rv": "10:15;100:120;500:400;1000:650;1500:890;2500:1475",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "FLY-DL",
  "produit": "FLYERS DL",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 10.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "100:39;200:49;300:59;500:69;1000:119;2000:169;3000:249;5000:379",
  "paliers_rv": "100:49;200:59;300:79;500:99;1000:179;2000:299;3000:399;5000:659",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "CAR-A6",
  "produit": "CARTON A6",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 10.0,
  "haut_cm": 15.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "100:49;200:59;300:79;500:89;1000:149;2000:229;3000:299;5000:449",
  "paliers_rv": "100:59;200:79;300:89;500:119;1000:239;2000:469;3000:749;5000:1129",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "Grammage 300 g"
 },
 {
  "code": "CAR-A5",
  "produit": "CARTON A5",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 15.0,
  "haut_cm": 21.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "100:89;200:109;300:119;500:149;1000:229;2000:299;3000:449;5000:749",
  "paliers_rv": "100:119;200:139;300:149;500:199;1000:299;2000:449;3000:709;5000:1169",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "Grammage 300 g"
 },
 {
  "code": "CAR-A4",
  "produit": "CARTON A4",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 29.7,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "10:15;100:109;500:339;1000:609;1500:899;2500:1509",
  "paliers_rv": "10:22;100:189;500:609;1000:979;1500:1339;2500:2219",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "Grammage 300 g"
 },
 {
  "code": "CAR-A3",
  "produit": "CARTON A3",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 29.7,
  "haut_cm": 42.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "1:3;50:89;100:159;250:219;500:429;750:449",
  "paliers_rv": "1:4;50:169;100:199;250:379;500:499;750:709",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "A VALIDER : present dans la liste des dimensions du document source mais absent du catalogue produits."
 },
 {
  "code": "CAR-DL",
  "produit": "CARTON DL",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 10.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "100:59;200:79;300:89;500:109;1000:179;2000:259;3000:379;5000:569",
  "paliers_rv": "100:79;200:89;300:119;500:149;1000:269;2000:449;3000:599;5000:989",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": ""
 },
 {
  "code": "AFF-A3",
  "produit": "AFFICHES A3",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 29.7,
  "haut_cm": 42.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_LIBRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "1:2;50:59;100:100;250:140;500:280;750:299",
  "paliers_rv": "1:3;50:110;100:130;250:250;500:330;750:470",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "Impression au recto seul : une affiche se colle au mur, son verso ne se voit pas."
 },
 {
  "code": "DEP-A4",
  "produit": "DEPLIANTS",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 29.7,
  "haut_cm": 21.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PAYSAGE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RV_OBLIGATOIRE",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "ROULE3:100,99,98",
  "marge_pli_mm": 5.0,
  "mode_prix": "PALIER",
  "paliers": "10:18;100:148;500:492;1000:800;1500:1095;2500:1814",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "Deduit : grille FLY-A4 recto verso + pliage 23 pourcent, deja inclus. NE PAS ajouter la finition Pliage au devis, elle compterait deux fois. Arrondi a l euro."
 },
 {
  "code": "BRO-A4",
  "produit": "BROCHURE A4",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 21.0,
  "haut_cm": 29.7,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "MULTIPLE4",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": 8.0,
  "mode_prix": "PALIER",
  "paliers": "10:48;25:118;50:145;100:240;250:405;500:760",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "Deduit pour 8 PAGES = 2 feuilles A3 recto verso par exemplaire, grille AFF-A3 recto verso + agrafage 0,30 EUR par exemplaire. GRILLE VALABLE POUR 8 PAGES SEULEMENT : au-dela, multiplier la part feuilles. Interpolation lineaire entre paliers, extrapolation au-dela de 750 feuilles."
 },
 {
  "code": "BRO-A5",
  "produit": "BROCHURE A5",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "FIXE",
  "larg_cm": 14.8,
  "haut_cm": 21.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "MULTIPLE4",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": 8.0,
  "mode_prix": "PALIER",
  "paliers": "10:30;25:69;50:135;100:220;250:475;500:800",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "Deduit pour 8 PAGES = 2 feuilles A4 recto verso par exemplaire, grille FLY-A4 recto verso + agrafage 0,30 EUR par exemplaire. GRILLE VALABLE POUR 8 PAGES SEULEMENT : au-dela, multiplier la part feuilles. Interpolation lineaire entre paliers."
 },
 {
  "code": "ETI-PAP",
  "produit": "ETIQUETTES PAPIER",
  "famille": "IMPRIMERIE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P1",
  "regle_dim": "PLAGE",
  "larg_cm": 5.0,
  "haut_cm": 5.0,
  "larg_max_cm": 29.0,
  "haut_max_cm": 40.0,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 4.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 150.0,
  "dpi_cible": 300.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 1.4,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "PALIER",
  "paliers": "5:20;10:35;20:60;50:125;75:165;100:220;125:269;250:500;500:1000",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": null,
  "note": "A VALIDER : grille Adhesif numerique gloss ou offset relevee sur la planche."
 },
 {
  "code": "RU-STD",
  "produit": "ROLL UP STANDARD",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "FIXE",
  "larg_cm": 85.0,
  "haut_cm": 205.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": 149.0,
  "note": "A TRANCHER : 205 cm est-il la hauteur imprimee totale ou la hauteur visible ? Prevoir la hauteur masquee par la cassette dans les dimensions commandees."
 },
 {
  "code": "RU-GEANT",
  "produit": "ROLL UP GEANT",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "FIXE",
  "larg_cm": 150.0,
  "haut_cm": 205.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": 249.0,
  "note": "A TRANCHER : le document source indique 150x200 dans le catalogue et 150x205 dans la liste des dimensions. Valeur retenue ici : 205."
 },
 {
  "code": "KAK-60",
  "produit": "KAKEMONO 60",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "FIXE",
  "larg_cm": 60.0,
  "haut_cm": 160.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": 69.0,
  "note": "Prevoir le debord des fourreaux haut et bas dans les dimensions commandees si pose sur barres."
 },
 {
  "code": "KAK-80",
  "produit": "KAKEMONO 80",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "FIXE",
  "larg_cm": 80.0,
  "haut_cm": 180.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PORTRAIT",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": 89.0,
  "note": "Prevoir le debord des fourreaux haut et bas dans les dimensions commandees si pose sur barres."
 },
 {
  "code": "PAN-BIPLEX",
  "produit": "PANNEAU BIPLEX",
  "famille": "SIGNALETIQUE",
  "matiere": "BIPLEX",
  "epaisseur_mm": 3.0,
  "classe": "P2",
  "regle_dim": "MAXI",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": 120.0,
  "haut_max_cm": 80.0,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 69.0,
  "prix_unite": null,
  "note": "Epaisseur 3 mm | 69 EUR/m2, sans minimum de facturation. La planche indique par ailleurs 129 EUR/m2 sous 1 m2 et 49 EUR/m2 au-dela : valeur unique retenue en attendant les paliers de surface. FRAIS DE TRAITEMENT 10 EUR MINI a ajouter sur la facture, non calcule par l outil."
 },
 {
  "code": "PAN-ALU",
  "produit": "PANNEAU ALU",
  "famille": "SIGNALETIQUE",
  "matiere": "ALUPANEL",
  "epaisseur_mm": 3.0,
  "classe": "P2",
  "regle_dim": "MAXI",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": 240.0,
  "haut_max_cm": 120.0,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "0:399;0.25:199;0.5:179;0.99:159",
  "paliers_m2_lam": "0:399;0.25:229;0.5:199;0.99:179",
  "prix_m2": 159.0,
  "prix_unite": null,
  "note": "Epaisseur 3 mm | Grille au m2, palier decide par la SURFACE TOTALE commandee. Non lamine : 399 sous 0,25 m2 - 199 sous 0,50 - 179 sous 0,99 - 159 au-dela. Lamine ou impression directe : 399 - 229 - 199 - 179. Cocher Lamination bascule sur la seconde grille."
 },
 {
  "code": "PAN-PVC",
  "produit": "PANNEAU PVC",
  "famille": "SIGNALETIQUE",
  "matiere": "PVC",
  "epaisseur_mm": 6.0,
  "classe": "P2",
  "regle_dim": "MAXI",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": 240.0,
  "haut_max_cm": 120.0,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "0:399;0.25:199;0.5:179;0.99:159",
  "paliers_m2_lam": "0:399;0.25:229;0.5:199;0.99:179",
  "prix_m2": 159.0,
  "prix_unite": null,
  "note": "Epaisseur 6 mm | Grille au m2, palier decide par la SURFACE TOTALE commandee. Non lamine : 399 sous 0,25 m2 - 199 sous 0,50 - 179 sous 0,99 - 159 au-dela. Lamine ou impression directe : 399 - 229 - 199 - 179. Cocher Lamination bascule sur la seconde grille."
 },
 {
  "code": "STICKER",
  "produit": "STICKERS",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "MINI",
  "larg_cm": 3.0,
  "haut_cm": 3.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 99.0,
  "prix_unite": null,
  "note": "CORRIGE : la marge de securite de 5 cm du document source est inapplicable sur un sticker de 3x3 cm. Ramenee a 5 mm. | Etiquette + decoupe : 99 EUR/m2, mini de facturation 15 EUR."
 },
 {
  "code": "VIN-STD",
  "produit": "VINYLE STANDARD",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P2",
  "regle_dim": "MINI",
  "larg_cm": 3.0,
  "haut_cm": 3.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 2.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 5.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 59.0,
  "prix_unite": null,
  "note": "CORRIGE : marge de securite ramenee a 5 mm, meme motif que les stickers. | Public : 129 le m2 sous 0,5 m2, 69 sous 1 m2, 59 a partir de 1 m2. Valeur retenue : 59."
 },
 {
  "code": "BAND-2M",
  "produit": "BANDEROLE 2 M",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "FIXE",
  "larg_cm": 200.0,
  "haut_cm": 90.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PAYSAGE",
  "tolerance_mm": 10.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 8.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": 69.0,
  "note": "Format impose : 200 x 90 cm, 6 oeillets, sans ourlet. Pour un autre format, utiliser BACHE SUR MESURE."
 },
 {
  "code": "BAND-3M",
  "produit": "BANDEROLE 3 M",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "FIXE",
  "larg_cm": 300.0,
  "haut_cm": 90.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "PAYSAGE",
  "tolerance_mm": 10.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 8.0,
  "dim_saisie": "NON",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "UNITE",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": null,
  "prix_unite": 99.0,
  "note": "Format impose : 300 x 90 cm, 8 oeillets, sans ourlet. Pour un autre format, utiliser BACHE SUR MESURE."
 },
 {
  "code": "AFF-GDFT",
  "produit": "AFFICHE GRAND FORMAT",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "MINI",
  "larg_cm": 40.0,
  "haut_cm": 40.0,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 1.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 39.0,
  "prix_unite": null,
  "note": "Papier dos bleu Hexis. Public : 79 le m2 sous 1 m2, 39 a partir de 1 m2. Unite 40x60=19, 60x80=39, 80x120=59."
 },
 {
  "code": "VIN-BRUT",
  "produit": "VINYLE BRUT",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 2.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 19.0,
  "prix_unite": null,
  "note": "Le mini de 2 m2 est un minimum de FACTURATION, pas un critere de conformite fichier."
 },
 {
  "code": "MICROPERF",
  "produit": "MICROPERFORE",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 1.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 59.0,
  "prix_unite": null,
  "note": "Le mini de 1 m2 est un minimum de FACTURATION | Public : lunette 79, sous 1 m2 89, a partir de 1 m2 59. Brut machine 29, mini 2 m2."
 },
 {
  "code": "BACHE-BRUT",
  "produit": "BACHE BRUT",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 1.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 19.0,
  "prix_unite": null,
  "note": "Le mini de 1 m2 est un minimum de FACTURATION, pas un critere de conformite fichier. | Brut machine sans oeillet."
 },
 {
  "code": "BACHE-MES",
  "produit": "BACHE SUR MESURE",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 10.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 1.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 49.0,
  "prix_unite": null,
  "note": "Bache finie, avec oeillets tous les metres inclus. Public sans facon 49 le m2, avec facon 59. Renforts 4 angles +15. Oeillet supplementaire 2 EUR."
 },
 {
  "code": "PAN-PLEXI",
  "produit": "PLEXIGLAS",
  "famille": "SIGNALETIQUE",
  "matiere": "PLEXI",
  "epaisseur_mm": 6.0,
  "classe": "P2",
  "regle_dim": "MAXI",
  "larg_cm": 40.0,
  "haut_cm": 30.0,
  "larg_max_cm": 200.0,
  "haut_max_cm": 100.0,
  "orientation": "LIBRE",
  "tolerance_mm": 5.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 20.0,
  "dpi_mini": 100.0,
  "dpi_cible": 120.0,
  "pages": "RECTO",
  "mini_facturation_m2": null,
  "texte_mini_mm": 4.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 375.0,
  "prix_unite": null,
  "note": "Epaisseur 6 mm | Plexi format libre 375 EUR/m2. Impression directe 21x30 = 39 EUR, 40x30 = 49 EUR a l unite."
 },
 {
  "code": "BANDEROLE-MES",
  "produit": "BANDEROLE SUR MESURE",
  "famille": "SIGNALETIQUE",
  "matiere": "",
  "epaisseur_mm": null,
  "classe": "P3",
  "regle_dim": "LIBRE",
  "larg_cm": null,
  "haut_cm": null,
  "larg_max_cm": null,
  "haut_max_cm": null,
  "orientation": "LIBRE",
  "tolerance_mm": 10.0,
  "fond_perdu_mm": 0.0,
  "fond_perdu_bas_mm": 0,
  "marge_secu_mm": 50.0,
  "dpi_mini": 30.0,
  "dpi_cible": 50.0,
  "pages": "RECTO",
  "mini_facturation_m2": 1.0,
  "texte_mini_mm": 8.0,
  "dim_saisie": "OUI",
  "plis": "",
  "marge_pli_mm": null,
  "mode_prix": "M2",
  "paliers": "",
  "paliers_rv": "",
  "paliers_m2": "",
  "paliers_m2_lam": "",
  "prix_m2": 49.0,
  "prix_unite": null,
  "note": "Bache finie, avec oeillets tous les metres inclus. Public sans facon 49 le m2, avec facon 59. Renforts 4 angles +15. Oeillet supplementaire 2 EUR."
 }
];
